"""
config.py — one place to change paths.

The real file is now available. To switch back to sample data:
    CSV_PATH = os.path.join(DATA_DIR, "ipl_2025_auction_players_SAMPLE.csv")
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(HERE, "data")
OUTPUT_DIR = os.path.join(HERE, "output")

# Sample data (generated by make_sample_data.py). On hackathon day, replace with
# the real CSV path and set CSV_SHEET if reading from xlsx.
CSV_PATH = os.path.join(DATA_DIR, "ipl_2025_auction_players_SAMPLE.csv")
CSV_SHEET = None

PLAYERS_JSON = os.path.join(OUTPUT_DIR, "players.json")
VIRTUAL_PURSE_CRORE = 100.0
